apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mu-webhook
webhooks:
  - name: mu-webhook.app.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    namespaceSelector:
      matchExpressions:
        - key: namespace
          operator: In
          values: ["app"]
#     objectSelector:
#       matchLabels:
#         mu-webhook-enabled: "true"
    clientConfig:
      service:
        name: mu-webhook
        namespace: app
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVSHloY2R2a2dOSHZCVXRzZE4zQzVOMjlxRU1rd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qTXhNREExCk1URXhPREF3V2hjTk1qZ3hNREF6TVRFeE9EQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNbktUTnR1CkZKdDM0QllTZXhBSW8zZVhhUzNkYmlzQjhpK3krRVNpUUlIYUdKNEFvV3BlZCs5czEzdUJpOVZ3eDJUeGtFNW4KU3VOM2p1VTVNY3pWbi85MFM0MjRTMHdsdjg3bTZ0S1UyUGQxSkZmRVhPaUpNVWttYXVWUFBoR0NNRkVIK2MwVgpEeEtWcWhpdURzc2tUMUxJN1NGMDdnRFg4K1UwSElKWGQyUG45RDg4RnJqODlUaDZCSE1JYkwwbHVpVEZoZmdICi9jWVU4di8yRHZhaTJKbWQ4ckZuUXhkSkZXY1ZTVi8xSDNOQVIzL2ZVSzR6WHF1Wjl5ZC92TlBPZStkd0hYdzYKN055cStRV1oxd3J5bmdYMHl0MDBuRG5yMTVyRld6UXNkL1dkbHY4dDhGalp3UU9lTjFYejhKR0ViRnpNOHNrZgpobW12ajZTMWVyb2pXME1DQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkp6M2dIMDRvdEJ3WTlzVDAwWnRKWkFjaHFCZU1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUJEbEMwY2I3QTdpWnREYjBLSTVtYnQ1OGYyR3lGd1dmd3VrL3Y1ZUkrS2s3UkNqM1Y2MmFObQpJTHVhaTRLSVZ0M1VGNHFpV2k0QVRFbjhUY0pxMGJoSHBlcEZWTFNNZWcrTy9qS3BZbWltSjBjaGZBbjVwNEo5Ck5Sb2ttaHBKcmFReW5rdllJYzJqeXNkVStPM1o4NEJSRHRPbXRHUnZ1WXhTeDQxUEg2T3ovUWd2b1FIQkdhVkUKakJ1M0M2OGJjdWdIUVRUSDQ4eVRKcG85NjdDNXFTV3hjb0JkZGJjbzdNSTk2TkpiVkNGUk5VVzJ0ZHZaMUZQMQplUCtzN1dEc3BGNnVvbjFaS3RHbkxKWUJVcWFpUEMvZ0M2Z1h2RW1zSGdUMEJMMWp2aUFxNG9lR0o3bjhFVyt6Ck5Pd0taRzlnVlUrbFA4S0xUTm5lSnBaMDJxQ0hXQlZiCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope:       "Namespaced"
