apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: apache
    tier: falco
  name: wordpress
spec:
  containers:
  - image: httpd
    name: apache
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
